### ISSUE TITLE
TODO List to get this done

### ISSUE THREAD

**Issue by tordans** [xijo/simple_form-bootstrap4#1]
# This demo page
- [ ] Add most examples from https://v4-alpha.getbootstrap.com/components/forms/
- [ ] Rename `blogs` to something demo-like
- [ ] Add, polish readme

# Get simple_form ready for bootstrap4
- [ ] Finish the config
- [ ] Solve the `<input>Text` spacing problem https://github.com/plataformatec/simple_form/pull/1369
- [ ] PR to add it inside simple form https://github.com/plataformatec/simple_form/pull/1337

# Cleanup
- Get the [previous bootstrap demo](https://github.com/rafaelfranca/simple_form-bootstrap) updated so it clearly reflects that is is for version 3
